### ISSUE TITLE
[Component] [Window] Mutli-Monitor Issues on Windows 10

### ISSUE THREAD

**Issue by Sintrastes** [kirill-grouchnikov/aurora#67] opened 2023-01-31 17:16 UTC
Hello,

I am having some issues with Aurora (currently on version 1.3) where my application works perfectly so long as I stick to one monitor on Windows 10, but as soon as I drag the window to a second monitor, things stop working.

After dragging my main application window to a second monitor, "drop-down menus" no longer display in the correct places. Additionally, if after I moved my application window to a second monitor, and then back to the first again -- the application stops rendering correctly entirely -- with part of the window displaying correctly, but other parts displaying as a flat white box.

When this happens it is almost like the window is trying to render to a smaller space than was actually allocated to it -- and the remainder is just rendered white.

The former issues seems to be an issue no matter what I do, but I did notice that the second issue only seems to occur with `AuroraWindowTitlePaneConfigurations.AuroraPlain()`; with `AuroraWindowTitlePaneConfigurations.System` it doesn't seem to be an issue.

**Comment by kirill-grouchnikov** [comment] 2023-01-31 17:52
The CL linked above should address the placement of popup content in multi-monitor setup in 1.4-SNAPSHOT. Let me know if it works for you.

The second part may or may not be in core Compose. Can you run this demo (which doesn't use Aurora):

```
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.window.WindowDraggableArea
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.DpSize
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.*

fun main() = application {
    val state = rememberWindowState(
        placement = WindowPlacement.Floating,
        position = WindowPosition.Aligned(Alignment.Center),
        size = DpSize(600.dp, 400.dp)
    )
    Window(
        onCloseRequest = ::exitApplication,
        undecorated = true,
        resizable = true,
        state = state
    ) {
        Column(Modifier.fillMaxSize()) {
            WindowDraggableArea {
                Box(modifier = Modifier.fillMaxWidth().height(24.dp).background(Color.Blue))
            }
            Box(modifier = Modifier.fillMaxWidth().height(32.dp).background(Color.Green))
            Box(modifier = Modifier.fillMaxWidth().weight(1.0f).background(Color.Red))
        }
    }
}
```

The blue part up top is wrapped in a `WindowDraggableArea` so it should allow you to drag this undecorated window between monitors. That's really all Aurora does under `AuroraPlain` title pane configuration - place a `Box` up top in a `Column` and use `WindowDraggableArea` for the dragging part.

In case the behavior you're seeing in Aurora is not reproducible in this small demo, the only thing I can think of is to make your demo as small as possible (down to something like a single button, or even no window content at all). Essentially stripping down everything in your app and get it as close as possible to this Aurora-less demo until the issue is no longer reproducible - which will then point to the potential cause of this issue.

**Comment by Sintrastes** [comment] 2023-02-06 21:10
@kirill-grouchnikov Unfortunately, my application is currently failing to run at all on 1.4-SNAPSHOT.

I've tried narrowing down the issue, but even with just an `auroraApplication` with single `AuroraWindow` with no contents, I'm getting the following exception on start up:

```
Exception in thread "main" java.lang.NullPointerException
        at org.jetbrains.skia.SurfaceProps._getPixelGeometryOrdinal(SurfaceProps.kt:10)
        at org.jetbrains.skia.SurfaceKt._nMakeFromBackendRenderTarget(Native Method)
        at org.jetbrains.skia.SurfaceKt.access$_nMakeFromBackendRenderTarget(Surface.kt:1)
        at org.jetbrains.skia.Surface$Companion.makeFromBackendRenderTarget(Surface.kt:281)
        at org.jetbrains.skiko.context.OpenGLContextHandler.initCanvas(OpenGLContextHandler.kt:50)
        at org.jetbrains.skiko.context.ContextHandler.draw(ContextHandler.kt:49)
        at org.jetbrains.skiko.redrawer.WindowsOpenGLRedrawer.redrawImmediately(WindowsOpenGLRedrawer.kt:62)
        at org.jetbrains.skiko.SkiaLayer.paint(SkiaLayer.awt.kt:367)
        at androidx.compose.ui.awt.ComposeLayer$ComponentImpl.paint(ComposeLayer.desktop.kt:242)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
```

The weird thing is that this looks like a generic issue with compose. There are no references to aurora specfically, yet after moving to `1.4-SNAPSHOT` my application no longer works.

**Comment by Sintrastes** [comment] 2023-02-06 21:11
Is there a particular compose version I should be using with `1.4-SNAPSHOT`?

**Comment by kirill-grouchnikov** [comment] 2023-02-06 23:00
That looks like something that might be addressed by https://github.com/JetBrains/skiko/pull/656 

Are you running on Windows 11 by any chance?

That crash isn't something that I can work around in Aurora. 

Aurora 1.4-SNAPSHOT is using Compose 1.3.0 and Kotlin 1.8.0.

**Comment by kirill-grouchnikov** [comment] 2023-02-06 23:03
And probably this crash would also happen without Aurora, even with the simplest examples from https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new

**Comment by kirill-grouchnikov** [comment] 2023-02-06 23:05
Have you tried running the earlier sample code under Compose 1.3.0 and Kotlin 1.8.0?

```
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.window.WindowDraggableArea
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.DpSize
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.*

fun main() = application {
    val state = rememberWindowState(
        placement = WindowPlacement.Floating,
        position = WindowPosition.Aligned(Alignment.Center),
        size = DpSize(600.dp, 400.dp)
    )
    Window(
        onCloseRequest = ::exitApplication,
        undecorated = true,
        resizable = true,
        state = state
    ) {
        Column(Modifier.fillMaxSize()) {
            WindowDraggableArea {
                Box(modifier = Modifier.fillMaxWidth().height(24.dp).background(Color.Blue))
            }
            Box(modifier = Modifier.fillMaxWidth().height(32.dp).background(Color.Green))
            Box(modifier = Modifier.fillMaxWidth().weight(1.0f).background(Color.Red))
        }
    }
}
```

**Comment by kirill-grouchnikov** [comment] 2023-03-25 00:40
The latest snapshot of Aurora at https://oss.sonatype.org/content/repositories/snapshots/org/pushing-pixels/ 1.4-SNAPSHOT depend on version `1.4.0-alpha01-dev980` of compose-multiplatform.

Let me know if you can retest your app under it, as well as the sample at https://github.com/kirill-grouchnikov/aurora/issues/67#issuecomment-1410820378

**Closed as completed** 2023-03-31 13:44 UTC
